# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports
